name: Python Lint & Test

on:
  pull_request:
    paths:
      - 'backend/**'
      - '.github/workflows/python-ci.yml'
  push:
    branches: [main]
    paths:
      - 'backend/**'
      - '.github/workflows/python-ci.yml'

jobs:
  lint-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "backend/pyproject.toml"

      - name: Sync dependencies
        run: uv sync --extra dev

      - name: Run ruff
        run: uv run ruff check .

      - name: Run pytest
        run: uv run pytest
